#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/parser'
require_relative 'lib/code'
require_relative 'lib/symbol_table'

class HackAssembler
  def initialize(input_file_path)
    @parser = Parser.new(input_file_path)
    @code = Code.new
    @symbol_table = SymbolTable.new
    @next_variable_address = 16
    @output_file_path = input_file_path.sub(/\.asm$/, '.hack')
  end

  def assemble
    run_first_pass
    @parser.reset
    binary_codes = run_second_pass
    File.write(@output_file_path, binary_codes.join("\n"))
  end

  private

  def run_first_pass
    # add label symbols to the symbol table
    line_number = -1
    while @parser.has_more_lines?
      @parser.advance
      if @parser.instruction_type == :L_INSTRUCTION
        @symbol_table.add_entry(@parser.symbol, line_number + 1)
      else
        line_number += 1
      end
    end
  end

  def run_second_pass
    # translate instructions to binary code
    binary_codes = []
    while @parser.has_more_lines?
      @parser.advance
      case @parser.instruction_type
      when :A_INSTRUCTION
        binary_codes << translate_a_instruction
      when :C_INSTRUCTION
        binary_codes << translate_c_instruction
      end
    end
    binary_codes
  end

  def translate_a_instruction
    symbol = @parser.symbol
    address =
      if numeric?(symbol)
        symbol.to_i
      else
        if @symbol_table.contains?(symbol)
          @symbol_table.get_address(symbol)
        else
          @symbol_table.add_entry(symbol, @next_variable_address)
          @next_variable_address += 1
          @next_variable_address - 1
        end
      end
    address.to_s(2).rjust(16, '0')
  end

  def translate_c_instruction
    comp = @code.comp(@parser.comp)
    dest = @code.dest(@parser.dest)
    jump = @code.jump(@parser.jump)
    "111#{comp}#{dest}#{jump}"
  end

  def numeric?(symbol)
    symbol.match?(/^\d+$/)
  end
end

if __FILE__ == $PROGRAM_NAME
  HackAssembler.new(ARGV[0]).assemble
end
